Feat: error handlers components
PatrykKuniczak/YT_Search_Plugin pull request #149
Opened 2023-11-09 12:57 UTC by TheMadNerd

#36

2023-11-14 12:48 UTC, masterHAWK99 requested changes

2023-11-14 12:48 UTC, masterHAWK99 commented on react-app/src/pages/popup/pages/error/ErrorPage.tsx
> +          <div>
```suggestion
          <p>
```

2023-11-14 12:48 UTC, masterHAWK99 commented on react-app/src/pages/popup/pages/error/ErrorPage.tsx
> +            <p style={{ fontSize: '16px' }}>
```suggestion
            <span style={{ fontSize: '16px' }}>
```

2023-11-14 20:05 UTC, PatrykKuniczak commented on react-app/src/pages/popup/pages/error/ErrorPage.tsx
> +            Wystąpił błąd krytyczny, odśwież stronę, gdy to nie pomoże, skontaktuj się z developerem
```suggestion
            Wystąpił błąd krytyczny, uruchom ponownie wtyczkę, gdy to nie pomoże, skontaktuj się z developerem
```

2023-11-14 20:07 UTC, PatrykKuniczak approved these changes
LGTM

2023-11-15 14:17 UTC, masterHAWK99 approved these changes

2023-11-21 15:38 UTC, PatrykKuniczak requested changes

2023-11-21 15:38 UTC, PatrykKuniczak commented on react-app/public/locales/en/translation.json
> +  "fallbackError": {
This message is used as fallback to toasts on useQuery, you can't overwrite it easly, this change, break the app, let's check reference before make changes in the future, for this let's create heading as seprate prop

2023-11-22 14:31 UTC, masterHAWK99 approved these changes

2023-11-22 16:05 UTC, PatrykKuniczak requested changes

2023-11-22 16:05 UTC, PatrykKuniczak commented on react-app/public/locales/pl/translation.json
> +  "heading": "BŁĄD",
```suggestion
  "fatalErrorHeading": "BŁĄD",
```

cause IMO, it's more meaningful, if you have many props, then this 'heading' could be everything or nothing :)

2023-11-23 21:14 UTC, PatrykKuniczak approved these changes
LGTM

2023-11-24 07:36 UTC, merged