feat: add searching mechanism for videos
PatrykKuniczak/YT_Search_Plugin pull request #153
Opened 2023-11-15 13:23 UTC by TheMadNerd

#80

2023-11-15 20:48 UTC, PatrykKuniczak approved these changes
LGTM

2023-11-15 20:56 UTC, PatrykKuniczak requested changes

2023-11-15 20:56 UTC, PatrykKuniczak commented on react-app/src/pages/popup/components/video/section/article/video-article.tsx
> +  title: string;
Create interface for that

2023-11-15 20:56 UTC, PatrykKuniczak commented on react-app/src/pages/popup/components/video/section/article/authorInfo/author-info.tsx
> +  authorName: string;
use here a part of this new interface

2023-11-15 20:56 UTC, PatrykKuniczak commented on react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
> +  title: string;
also use a part of new interface

2023-11-15 20:56 UTC, PatrykKuniczak commented on react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
> +  whenPublished: string;
this prop should be 'publishedAt'

2023-11-15 20:56 UTC, PatrykKuniczak commented on react-app/src/pages/popup/routes/videos.route.tsx
> +      {filteredVideos?.map(({ id, thumbnail, avatar, authorName, whenPublished, views, title }) => (
in map destructure only id, and use it for 'key' but the restprops use on the component below, like key={id} ...restProps

2023-11-16 14:34 UTC, masterHAWK99 commented on react-app/src/pages/popup/routes/videos.route.tsx
> +      ))}
Skeletons won't show up when `filteredVideos` will be undefined. You should show skeletons when the whole list of videos is loading, not each one.

2023-11-17 13:32 UTC, masterHAWK99 requested changes

2023-11-17 13:32 UTC, masterHAWK99 commented on react-app/src/pages/popup/routes/videos.route.tsx
> +  if (isLoading === true) {
```suggestion
  if (isLoading) {
```

2023-11-17 21:11 UTC, PatrykKuniczak requested changes

2023-11-17 21:11 UTC, PatrykKuniczak commented on react-app/src/pages/popup/components/video/section/article/videoInfo/video-infos.tsx
> +  const publishedDate = new Date(publishedAt);
that's unnecessary, put this prop directly below

2023-11-17 21:11 UTC, PatrykKuniczak commented on react-app/src/pages/popup/routes/videos.route.tsx
> +  const videos = useMemo(
why memo, for static values?

2023-11-20 09:36 UTC, TheMadNerd commented on react-app/src/pages/popup/routes/videos.route.tsx
> +  const videos = useMemo(
without memo this error pops out
"The 'videos' function makes the dependencies of useMemo Hook (at line 39) change on every render. Move it inside the useMemo callback. Alternatively, wrap the definition of 'videos' in its own useCallback() Hook."

2023-11-20 20:38 UTC, PatrykKuniczak commented on react-app/src/pages/popup/routes/videos.route.tsx
> +  const videos = useMemo(
below also you shouldn't use memo, but leave it here, we will change it in the future

2023-11-20 20:42 UTC, PatrykKuniczak approved these changes
LGTM

2023-11-20 20:57 UTC, masterHAWK99 approved these changes

2023-11-21 07:53 UTC, merged