improvement: change playlist on 'watch later' btn on navbar
PatrykKuniczak/YT_Search_Plugin pull request #162
Opened 2023-11-17 13:10 UTC by TheMadNerd

#132

2023-11-17 21:28 UTC, PatrykKuniczak requested changes

2023-11-17 21:28 UTC, PatrykKuniczak commented on react-app/utils/interfaces/index.ts
> +  userYtVideos: {
create it as a separate interface and use reference here

2023-11-17 21:28 UTC, PatrykKuniczak commented on react-app/src/pages/popup/layouts/navbar.tsx
> +export const StyledNavbar = ({ playlistId, focus }: Pick<IUser['userYtVideos'], 'playlistId'> & { focus: TVoid }) => {
use here a part of this new interface for userYtVideos

2023-11-17 21:33 UTC, PatrykKuniczak requested changes

2023-11-17 21:33 UTC, PatrykKuniczak commented on react-app/public/locales/en/translation.json
> +  "noPlaylistFound": "Your playlist doesn't exist yet, add something from your video list to create it"
```suggestion
  "noPlaylistFound": "Your playlist doesn't exist yet, add something from your list of videos to create it"
```

2023-11-20 11:43 UTC, masterHAWK99 approved these changes

2023-11-20 11:59 UTC, merged